

CREATE TABLE USUARIOS(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NOMBRE TEXT NOT NULL,
    APELLIDO TEXT NOT NULL,
    CEDULA TEXT NOT NULL UNIQUE     
);

CREATE TABLE CUENTAS(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NUMERO_CUENTA TEXT NOT NULL UNIQUE,
    SALDO REAL NOT NULL,
    TIPO_CUENTA TEXT NOT NULL,
    ID_USUARIO INTEGER NOT NULL,
    FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID)
);

CREATE TABLE TRANSACCIONES(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    FECHA TEXT NOT NULL,
    HORA TEXT NOT NULL,
    TIPO_TRANSACCION TEXT NOT NULL,
    MONTO REAL NOT NULL,
    ID_CUENTA INTEGER NOT NULL,
    TIPO_CUENTA_DESTINO TEXT,
    FOREIGN KEY(ID_CUENTA) REFERENCES CUENTAS(ID)
);
